apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a9ptp5u1l-nodejs 
  janus-idp.io/tekton: a9ptp5u1l-nodejs
  backstage.io/kubernetes-id: a9ptp5u1l-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a9ptp5u1l-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  